### ISSUE TITLE
Build breaks with node-neat and v1.1.1

### ISSUE THREAD

**Issue by linkurzweg** [giowe/gulp-sass-vars#4]
I cannot build my project anymore with the latest version of the package.

I get the following error message:
`gulp-sass-vars: Injected 1 variables to sass:
	$output-bourbon-deprecation-warnings: 'false';

node_modules/source-map/lib/source-map-generator.js:277
      throw new Error('Invalid mapping: ' + JSON.stringify({
            ^
Error: Invalid mapping: {"generated":{"line":1,"column":29271},"source":"../../../../../../node_modules/bourbon-neat/app/assets/stylesheets/grid/_span-columns.scss","original":{"line":89,"column":-353},"name":null}`

The error appears in conjuction wiht node-neat, my task looks like this:
`gulp.task(`css:${publication.name}`, () => {
			return gulp.src(`${config.paths.scss}/styles.scss`)
				.pipe(gulpif(process.env.watch === 'true', plumber({errorHandler: onWatchError})))
				.pipe(newer({
					dest: `${config.paths.target}/css/styles.css`,
					extra: extraFiles
				}))
				.pipe(sourcemaps.init())
				.pipe(sassVars(vars))
				.pipe(sass({
					outputStyle: 'expanded',
					includePaths: ['css:' + publication.name].concat(normalize, neat),
					errLogToConsole: true
				}))
				.pipe(sourcemaps.write('./'))
				.pipe(gulp.dest(`${config.paths.target}/css`))
				.pipe(touch());
		})`

If I go back to v1.1.0 everything works fine.

**Comment by giowe** [comment]
checking on it, tnx!

**Comment by giowe** [comment]
@VitorLuizC reverting on my previous version this 1.0.3 this issue doesn't exists. I pushed a stable branch and published on npm version 1.2.0 (exactly equal as 1.0.3). Can you find the problem here ?

**Comment by VitorLuizC** [comment]
@linkurzweg I'm trying to reproduce this issue.

@giowe can you just rollback the _stream treatment_ instead of using `gulp-header`? I think there's something to do with it.

**Comment by VitorLuizC** [comment]
@linkurzweg can you paste here your `styles.scss` and your `gulpfile.js` ?

I can't reproduce with my simple mock.
![image](https://user-images.githubusercontent.com/9027363/26895547-51207448-4b98-11e7-9829-bcdcfed3d06b.png)

**Comment by linkurzweg** [comment]
@VitorLuizC, I don't know if that will actually help, because our build system is a bit complicated. There are multiple tasks in different files spread across multiple projects that share the same codebase to some extent. Can I send you the files directly? Thanks for looking into this :)

**Comment by VitorLuizC** [comment]
@linkurzweg Can you provide the vars U're trying to inject? I could test if my PR is causing this. Also, bootstrap-sass, node-sass and other modules have issues like it.
https://github.com/brunch/sass-brunch/issues/141
https://github.com/sass/libsass/issues/2312
https://github.com/mozilla/source-map/issues/254
https://github.com/dlmanning/gulp-sass/issues/609 (An issue opened today)

Can you confirm if those issues are related with this one?

@giowe I will rollback your _stream treatment_ and make another PR.

**Comment by linkurzweg** [comment]
@VitorLuizC , sure, this is the only var I try to inject:
`$output-bourbon-deprecation-warnings: 'false';`

I can confirm that the issues are related. The "invalid mapping" error points to a line that is starting with an ampersand.

However, with v1.2.0 of the package, everything seems to be fine :)
