### ISSUE TITLE
Color values with quotes (updated npm packages)

### ISSUE THREAD

**Issue by tillschomborg** [giowe/gulp-sass-vars#6]
Hi there,

I provide variables via .json like "primaryColor" : "rgb(255,179,0)".

I recently updated my packages and unfortunately the task doesn't work as expected.

[14:52:34] $primaryColor: "rgb(255,179,0)";
[14:52:34] $secondaryColor: "#232323";

In the css-file it is like color: "#232323". The quotes are wrong.

**Comment by VitorLuizC** [comment]
@giowe published v 1.2 without my PR (#2). Until he merge my new PR (#5) and fix #4, you can install v 1.1.1.

```sh
npm i gulp-sass-vars@1.1.1 -D
```

**Comment by AlexDunmow** [comment]
Thanks @VitorLuizC - I'll be running off your fork until your PRs are merged. My sass seems to build fine now.

**Comment by giowe** [comment]
@VitorLuizC @AlexDunmow 1.3.0 out!
