### ISSUE TITLE
Last merge change 1.3.0 to 1.1.4 and it stopped working

### ISSUE THREAD

**Issue by damsorian** [giowe/gulp-sass-vars#9]

**Comment by giowe** [comment]
what error did you get?

**Comment by giowe** [comment]
@damsorian I pushed a new version, can you tell me if the problem you were facing is now solved?

**Comment by damsorian** [comment]
I don't know why the **1.1.4** version did not compile my code. but now, **it's working with the 1.1.5 version.**

The downgrade version from 1.3.0 to 1.1.5 is ok?
